# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui',
# licensing of 'main_window.ui' applies.
#
# Created: Fri Jul 17 23:35:46 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 672)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.table_dl = QtWidgets.QTableWidget(self.centralwidget)
        self.table_dl.setAutoFillBackground(False)
        self.table_dl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table_dl.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_dl.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_dl.setObjectName("table_dl")
        self.table_dl.setColumnCount(5)
        self.table_dl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_dl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dl.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.table_dl, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_file_path = QtWidgets.QLabel(self.centralwidget)
        self.label_file_path.setObjectName("label_file_path")
        self.horizontalLayout.addWidget(self.label_file_path)
        self.lineEdit_file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.horizontalLayout.addWidget(self.lineEdit_file_path)
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout.addWidget(self.browse_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.firefox_button = QtWidgets.QPushButton(self.centralwidget)
        self.firefox_button.setObjectName("firefox_button")
        self.horizontalLayout_2.addWidget(self.firefox_button)
        self.chrome_button = QtWidgets.QPushButton(self.centralwidget)
        self.chrome_button.setObjectName("chrome_button")
        self.horizontalLayout_2.addWidget(self.chrome_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_2.addWidget(self.download_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.text_input = QtWidgets.QTextEdit(self.centralwidget)
        self.text_input.setObjectName("text_input")
        self.gridLayout.addWidget(self.text_input, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Ytdl", None, -1))
        self.table_dl.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Title", None, -1))
        self.table_dl.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Size", None, -1))
        self.table_dl.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Speed", None, -1))
        self.table_dl.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "ETA", None, -1))
        self.table_dl.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Status", None, -1))
        self.label_file_path.setText(QtWidgets.QApplication.translate("MainWindow", "File Path :", None, -1))
        self.browse_button.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.firefox_button.setText(QtWidgets.QApplication.translate("MainWindow", "From Firefox", None, -1))
        self.chrome_button.setText(QtWidgets.QApplication.translate("MainWindow", "From Chrome", None, -1))
        self.download_button.setText(QtWidgets.QApplication.translate("MainWindow", "Download", None, -1))
        self.download_button.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Return", None, -1))

